# 5. Generate multiplication table for a number using a function.


# def table(n):
#     for i in range(1,11):
#         print(f"{n}X{i}={n*i}")
# num=int(input("Enter a num: ")) 
# table(num)       





def multable(n):
    for i in range(1,11):
        print(f"{n}x{i}={n*i}")
n=int(input("Enter your num:"))
multable(n)    




# n=int(input("Enter your num:"))
# for i in range(1,11):

#    print(f"{n}*{i}={n*i}")
